language: python
dist: xenial
addons:
  apt:
    packages:
      - file
      - binutils
      - tar
      - unzip
      - rpm2cpio
      - cpio
      - cabextract
      - openssl
cache:
  directories:
    - $HOME/.cache/cve-bin-tool
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
script:
  - python setup.py test
  - pip install -e .
  - pip install -e example/oot-checker
  - cve-bin-tool -l info $(mktemp -d) 2>&1 | grep -E 'loaded:.*checker_name'
jobs:
  include:
    - stage: test
  allow_failures:
    - stage: pylint
      python:
        - "3.6"
      install:
        pip install pylint
      script:
        pylint --version
        pylint cve-bin-tool/
        pylint test/
